name: Ejecutar app Node

on:
  push:
    branches:
      - main

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar aplicación
        run: npm start